### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Justinnunez1717** [Gods-Of-ACM/backEnd#25]
Instructions for installation includes a step to:
_"npm install -g squelize-cli"_
instead of 
_"npm install -g sequelize-cli"_.

Now SQUEALize like a pig
:pig: :pig: :pig:

**Comment by Justinnunez1717** [comment]
This is also true in the wording for the fourth, optional, instruction.

**Comment by Quinn-Donnelly** [comment]
#26 Will resolve this issue.

**Comment by wrejcodes** [comment]
closed via #26
